apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "14493577"
    labels:
        datastore_id: "3190403"
data:
    classification: UI/Usability
    created: "2013-07-19T15:55:35.168408Z"
    description: |-
        Summary:

        If you have a method like this:

        + (void)foo
        {
            static dispatch_once_t onceToken;
            dispatch_once(&onceToken, ^{
                    [NSException raise:@"MyException" format:@"Something went wrong"];
            });
        }

        and a unit test like this:

        - (void)testRaiseException
        {
            XCTAssertThrows([MyClass foo], @"Test Failed");
        }

        the test will never pass because the execution is interrupted before the assertion is evaluated.

        Steps to Reproduce:
        Create a project with the sample code above and run the Test configuration.

        Expected Results:
        The test should succeed and the 'unit test status mark' should show the green checkmark.

        Actual Results:
        The execution of the test is interrupted when the exception is encountered. Tests are said to be succeeded but that's simply because the assertion was never executed.
    email: g.tranchedone@gmail.com
    modified: "2013-07-19T15:55:35.168577Z"
    number: "14493577"
    number_intvalue: 14493577
    originated: 19-Jul-2013 04:55 PM
    parent_number: '&{NULL_VALUE}'
    product: Developer Tools
    product_version: Xcode Version 5.0 (5A11344j)
    reproducible: Always
    resolved: ""
    status: Open
    title: 'XCTAssertThrows: Raising an exception in a dispatch_once() block makes the test to never execute assertion'
