apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "32083596"
    labels:
        datastore_id: "4997165810188288"
data:
    classification: Serious Bug
    created: "2017-05-09T20:02:16.59359Z"
    description: "Summary:\r\n(NS)FileManager errors that would normally propagate with either an NSError or by throwing in Swift do not propagate the error when running a process in Xcode or via the lldb command line debugger.\r\n\r\nSignificantly, the expected errors are propagated when the application or tool is run outside a debugging environment.\r\n\r\n\r\nSteps to Reproduce:\r\n1. Open the attached CopyFailureErrors.xcodeproj\r\n2. Build and run.\r\n\r\n\r\nExpected Results:\r\nIn the console, you should see output reflecting the fact that an error was thrown upon attempting to copy /tmp/file1.txt over /tmp/file2.txt, which has been caused to already exist.\r\n\r\n\r\nObserved Results:\r\nNo error is propagated, leaving the impression that the copy has succeeded when in fact it has not.\r\n\r\n\r\nVersion:\r\nVersion 8.3.2 (8E2002)\r\n10.12.4 (16E195)\r\n\r\n\r\nNotes:\r\n\r\n\r\n\r\nConfiguration:\r\n\r\n\r\nAttachments:"
    email: jalkut@red-sweater.com
    modified: "2017-05-09T20:02:16.59378Z"
    number: "32083596"
    number_intvalue: 32083596
    originated: 09-May-2017 04:00 PM
    parent_number: '&{NULL_VALUE}'
    product: Developer Tools
    product_version: Version 8.3.2 (8E2002)
    reproducible: Alwayss
    resolved: ""
    status: Open
    title: FileManager errors do not propagate when debugging target process
