apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "23541186"
    labels:
        datastore_id: "5019871104466944"
data:
    classification: ""
    created: "2015-11-13T22:42:13.47522Z"
    description: "Summary:\r\nI have added 1,000 external testers for our app.  When I attempt to add one more, I get the error message \"You can’t accept the invite because the inviter has reached the maximum number of testers for this app.\"\r\n\r\nSteps to Reproduce:\r\n1. Have 1,000 external testers\r\n2. Go to External Testers page for app. Press \"+\" then \"Add more testers\"\r\n3. Enter a new email address.  Press OK.\r\n4. Press \"Save\".\r\n\r\n\r\nExpected Results:\r\nUser receives invitation to test.\r\n\r\nActual Results:\r\nUser receives nothing.  I get confusing error message \"You can’t accept the invite because the inviter has reached the maximum number of testers for this app.\"\r\n\r\nVersion:\r\n\r\n\r\nNotes:"
    email: rod@anovaculinary.com
    modified: "2015-11-13T22:42:13.47557Z"
    number: "23541186"
    number_intvalue: 23541186
    originated: 11/13/2015
    parent_number: '&{NULL_VALUE}'
    product: iTunes Connect
    product_version: ""
    reproducible: Yes
    resolved: ""
    status: Open
    title: iTunes Connect gives error message if I try to add 1001st external tester
