apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "36274153"
    labels:
        datastore_id: "5047933498032128"
data:
    classification: Serious Bug
    created: "2018-01-03T13:53:03.2081Z"
    description: "Summary:\r\nA user contacted our support team regarding issues with his subscription purchases. We got his receipt file and when we sent it for validation with the iTunes receipt validation server we ran into few unexpected results in the response we got from iTunes server as listed below:\r\n\r\n1. For all of the transactions the \"original purchase date\" is within the range of 2 days in Dec. 2017 (most of them at the exact same second), while the \"purchase date\" and for some of the transactions even the \"expiration date\" is prior to the \"original purchase date\".\r\n\r\n2. For each of the transactions in the \"receipt.in_app\" field of the receipt validation response the \"transaction identifier\" field is not listed in the \"latest_receipt_info\" array. Instead there's a parallel transaction in the \"latest_receipt_info\" array with the same \"product id\", \"original transaction id\", \"purchase date\" and \"expiration date\" but with different \"transaction id\" and \"original purchase date\".\r\n\r\n3. All the transactions that are listed as \"original transactions\" for any of the transactions listed in the response (either in the \"receipt.in_app\" array or in the \"latest_receipt_info\" array) can not be found neither in the \"receipt.in_app\" array nor in the \"latest_receipt_info\" array. For example if we look at the transaction with ID \"450000341982645\", which is found in the \"receipt.in_app\" array, its \"original transaction id\" is \"450000243188359\", but if we look for a transaction with that ID (the ID of the original transaction) we won't find any matching transaction.\r\n\r\n\r\nAttached are the receipt file (receipt.bin) and the response from iTunes receipt validation server (response.json).\r\n\r\nSteps to Reproduce:\r\nSend the attached receipt file to the receipt validation endpoint: \r\nhttps://buy.itunes.apple.com/verifyReceipt\r\n\r\nAccording to the instructions specified here:\r\nhttps://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1\r\n\r\nExpected Results:\r\nA standard parsed receipt response.\r\n\r\nActual Results:\r\nA non-standard parsed receipt response with the issues specified above.\r\n\r\n\r\n== LINKS TO THE RECEIPT / RESPONSE FILES WERE OMITED DUE TO USER PRIVACY =="
    email: dlahyani@lightricks.com
    modified: "2018-01-03T13:53:03.20843Z"
    number: "36274153"
    number_intvalue: 36274153
    originated: 03/01/2018
    parent_number: '&{NULL_VALUE}'
    product: iTunes Store
    product_version: ""
    reproducible: Yes
    resolved: ""
    status: Open
    title: Unexpected behavior in iTunes receipt validation server
