apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "21745663"
    labels:
        datastore_id: "4941575729709056"
data:
    classification: Other Bug
    created: "2015-07-09T15:11:33.59033Z"
    description: "The methods performBlockAndWait(_:) and performBlock(_:) do not accept a closure which throws.  “Invalid conversion from throwing function of type '() throws -> _' to non-throwing function type '() -> Void’”.  I believe something like saving the context is a common use case for this:\n\n\n    public func saveContexts() throws {\n        do {\n            backgroundContext.performBlockAndWait { [weak self] in\n                try self?.backgroundContext.save()\n            }\n            mainContext.performBlockAndWait { [weak self] in\n                try self?.mainContext.save()\n            }\n        }\n        catch let error {\n            throw error\n        }\n    }\n       \nMarking performBlockAndWait and performBlock as rethrows would allow them to take a throwing closure and propagate the error to the caller."
    email: stephen.groom@me.com
    modified: "2015-07-09T15:11:33.59052Z"
    number: "21745663"
    number_intvalue: 21745663
    originated: 09-Jul-2015 04:11 PM
    parent_number: '&{NULL_VALUE}'
    product: Developer Tools
    product_version: Swift 2b3
    reproducible: Always
    resolved: ""
    status: Open
    title: NSManagedObjectContext performBlock() & performBlockAndWait() don't accept throwing closures
